config/routes.rb
Rails.application.routes.draw do
  resources :replies

  devise_for :users

   root 'home#index'
   resources :posts, only: [:new, :create, :show, :index] do
     resources :replies, only: [:new, :create]
   end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :content

  def author
    user.email
  end

  def posted_on
    created_at.to_formatted_s(:long)
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates_presence_of :content

  def author
    user.email
  end

  def posted_on
    created_at.to_formatted_s(:long)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @reply = @post.replies.new
  end

  private

  def post_params
    params.require(:post).permit(:content, :title)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @reply = @post.replies.new
  end

  def create
    @post = Post.find(params[:post_id])
    @reply = @post.replies.new(reply_params)
    @reply.user = current_user
    if @reply.save
      redirect_to post_path(@reply.post)
    else
      render 'posts/show'
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Messageotron</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
    </ul>
    <p class="navbar-text pull-right">
    <p class="navbar-text pull-right">
      <%= current_user.email %> | 
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-default ' %>
    </p>
  </div>
</nav>
<article>
  <h1>Welcome</h1>
</article

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messageotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, post_path(post) %></td>
  <td><%= post.author %></td>
  <td><%= post.posted_on %></td>
</tr>

app/views/posts/index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date Posted</th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>
<%= link_to "New Post", new_post_path, class: 'btn btn-primary btn-lg active' %>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @post do |f| %>
    <form role='form'>
    <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <%= f.submit "Post" %>
  </form>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Posted by <%= @post.author %></p>
<p>on <%= @post.posted_on %></p>
<div>
  <%= @post.content %>
</div>
<%= link_to "New Reply", new_post_reply_path(@post), class: 'btn btn-primary btn-lg active' %>
<hr />
<h2>Replies</h2>
<div>
  <%= render @post.replies.select {|r| r.persisted? } %>
</div>
<h1>New Reply</h1>
<%= render 'replies/errors' %>
<%= render 'replies/form' %>

app/views/replies/_errors.html.erb
<% if @reply.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @reply.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/replies/_form.html.erb
<%= form_for [@post, @reply] do |f| %>
    <div class='form-group'>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <%= f.submit "Reply" %>
  </form>
<% end %>

app/views/replies/_reply.html.erb
<div><%= reply.content %></div>
<div><%= reply.author %> on <%= reply.posted_on %></div>

app/views/replies/new.html.erb
<%= render 'replies/errors' %>
<h1>Replying to <%= @reply.post.title %></h1>
<%= render 'replies/form' %>